### ISSUE TITLE
dairy(20170801-20170822)

### ISSUE THREAD

**Issue by zhouzhongyuan** [BokeFE/QA#53]

**Comment by zhouzhongyuan** [comment]
# 20170801 

## TODO
- [ ] 学习[feact第一部分](http://www.mattgreer.org/articles/react-internals-part-one-basic-rendering/)
- [x] wechat,菜单扫码，菜单获取地理位置
- [ ] 兰兰IELTS单词做完，可用。
- [ ] 兰兰套磁模板3-5个
- [x] 7点起床
- [x] 公司日志
- [x] 交发票

- [ ] 10点睡觉

## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:15 |  走路
08:15 - 08:30 |  整理杂事
08:30 - 08:45 |  制作生成此记录的代码
08:45 - 09:00 |  制作[生成此记录的代码](https://github.com/BokeFE/QA/blob/master/generateDairy.js)
09:00 - 09:15 |  头疼，歇着
09:15 - 09:30 |  wechat, [scancode_push](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141016)
09:30 - 09:45 |  贴发票
09:45 - 10:00 |  贴发票（总用时：20分钟），写工作日志
10:00 - 10:15 |  [自定义菜单事件推送](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141016)
10:15 - 10:30 |  添加type为[`location_select`的菜单](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141013)
10:30 - 10:45 |  电脑卡了。
10:45 - 11:00 |  web-ide, router
11:00 - 11:15 |  web-ide, router
11:15 - 11:30 |  走路
11:30 - 11:45 |  买菜
11:45 - 12:00 |  买菜
12:00 - 12:15 |  吃饭
12:15 - 12:30 |  吃饭
12:30 - 12:45 |  吃饭
12:45 - 13:00 |  玩
13:00 - 13:15 |  休息
13:15 - 13:30 |  休息
13:30 - 13:45 |  走路
13:45 - 14:00 |  配置web-ide环境，主要是webpack
14:00 - 14:15 |  配置webpack
14:15 - 14:30 |  配置webpack
14:30 - 14:45 |  配置webpack
14:45 - 15:00 |  配置webpack
15:00 - 15:15 |  转向[react-boilerplate](https://github.com/react-boilerplate/react-boilerplate)
15:15 - 15:30 |  [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate)
15:30 - 15:45 |  [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate)
15:45 - 16:00 |  休息
16:00 - 16:15 | 
16:15 - 16:30 | 
16:30 - 16:45 | 
16:45 - 17:00 | 
17:00 - 17:15 | 
17:15 - 17:30 | 
17:30 - 17:45 | 
17:45 - 18:00 | 
18:00 - 18:15 | 
18:15 - 18:30 | 
18:30 - 18:45 | 
18:45 - 19:00 | 

## 问题
- [ ] 使用同样(src)的webpack 、babel 、gulp配置，就是跑不起来，webpack的配置真麻烦。现在的web项目不可能不用webpack，所有以后还是要学习webpack怎么配。暂时可以使用别人配好的[react-boilerplate](https://github.com/react-boilerplate/react-boilerplate)

**Comment by zhouzhongyuan** [comment]
# 20170802 

## TODO

## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:15 | 
08:15 - 08:30 | 
08:30 - 08:45 | 
08:45 - 09:00 | 
09:00 - 09:15 | 
09:15 - 09:30 | 
09:30 - 09:45 | 
09:45 - 10:00 | 
10:00 - 10:15 | 
10:15 - 10:30 | 
10:30 - 10:45 | 
10:45 - 11:00 | 
11:00 - 11:15 | 
11:15 - 11:30 | 
11:30 - 11:45 | 
11:45 - 12:00 | 
12:00 - 12:15 | 
12:15 - 12:30 | 
12:30 - 12:45 | 
12:45 - 13:00 | 
13:00 - 13:15 | 
13:15 - 13:30 | 
13:30 - 13:45 | 
13:45 - 14:00 | 
14:00 - 14:15 | 
14:15 - 14:30 | 
14:30 - 14:45 | 
14:45 - 15:00 | 
15:00 - 15:15 | 
15:15 - 15:30 | 
15:30 - 15:45 | 
15:45 - 16:00 | 
16:00 - 16:15 | 
16:15 - 16:30 | 
16:30 - 16:45 | 
16:45 - 17:00 | 
17:00 - 17:15 | 
17:15 - 17:30 | 
17:30 - 17:45 | 
17:45 - 18:00 | 
18:00 - 18:15 | 
18:15 - 18:30 | 
18:30 - 18:45 | 
18:45 - 19:00 |

**Comment by zhouzhongyuan** [comment]
# 20170803 

## TODO

## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 | 走路
08:30 - 09:00 |  配置web-ide, css loader。
09:00 - 09:30 |  配置“开发版”环境。
09:30 - 10:00 |  配置“开发版”环境。
10:00 - 10:30 |  redux是什么
10:30 - 11:00 |  react-redux又是什么
11:00 - 11:30 |  yigo1.6打包网站有出问题了
11:30 - 12:00 | 
12:00 - 12:30 | 
12:30 - 13:00 | 
13:00 - 13:30 | 
13:30 - 14:00 |  redux官方文档首页看完
14:00 - 14:30 | 
14:30 - 15:00 | 
15:00 - 15:30 | 
15:30 - 16:00 | 
16:00 - 16:30 | 
16:30 - 17:00 | 
17:00 - 17:30 | 
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获
loader
1. include:[The Condition must match](https://webpack.js.org/configuration/module/#condition). 必须在其中才会进行转换。

**Comment by zhouzhongyuan** [comment]
# 20170807

## TODO

## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 |  睡觉
08:30 - 09:00 |  走路
09:00 - 09:30 |  新天丰打包错误
09:30 - 10:00 |  新天丰打包错误
10:00 - 10:30 |  新天丰打包错误（因为使用了中文文件名）
10:30 - 11:00 |  购买内存条
11:00 - 11:30 |  
11:30 - 12:00 | 
12:00 - 12:30 | 
12:30 - 13:00 | 
13:00 - 13:30 | 
13:30 - 14:00 |  
14:00 - 14:30 | 
14:30 - 15:00 | 
15:00 - 15:30 | 
15:30 - 16:00 | 
16:00 - 16:30 | 
16:30 - 17:00 | 
17:00 - 17:30 | 
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获

**Comment by zhouzhongyuan** [comment]
# 20170808

## TODO
- [ ] 和顾老师讨论web-ide
    - [ ] 设计前端Store结构，越详细越好
    - [ ] component与store如何交互
    - [ ] store与后台如何交互
## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 |  走路
08:30 - 09:00 |  和顾老师讨论web-ide
09:00 - 09:30 |  和顾老师讨论web-ide
09:30 - 10:00 |  和顾老师讨论web-ide
10:00 - 10:30 |  
10:30 - 11:00 |  
11:00 - 11:30 |  
11:30 - 12:00 | 
12:00 - 12:30 | 
12:30 - 13:00 | 
13:00 - 13:30 | 
13:30 - 14:00 |  
14:00 - 14:30 | 
14:30 - 15:00 | 
15:00 - 15:30 | 
15:30 - 16:00 | 
16:00 - 16:30 | 
16:30 - 17:00 | 
17:00 - 17:30 | 
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获

**Comment by zhouzhongyuan** [comment]
# 20170809
周三

## TODO
- [ ] 和顾老师讨论-ide
    - [x] 设计前端Store结构，越详细越好
    - [ ] component与store如何交互
    - [ ] store与后台如何交互
## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 |  走路
08:30 - 09:00 |  思考-ide
09:00 - 09:30 |  画-ide原型图
09:30 - 10:00 |  画-ide原型图
10:00 - 10:30 |  看react-boilerplate代码，熟悉等
10:30 - 11:00 |  看react-boilerplate代码，熟悉等， compose
11:00 - 11:30 |   compose。从右向左，合并多个函数。<br/>直接看下方源代码，主要是理解[Array的Right](https://aotu.io/notes/2016/04/14/js-/index.html).
11:30 - 12:00 |  走路
12:00 - 12:30 |  吃饭
12:30 - 13:00 |  休息
13:00 - 13:30 |  走路
13:30 - 14:00 |  redux-，tutorial
14:00 - 14:30 |  redux-，tutorial
14:30 - 15:00 |  redux-，tutorial
15:00 - 15:30 |  redux-，tutorial
15:30 - 16:00 |  why we need redux-?
16:00 - 16:30 |  , real-world看不懂啊
16:30 - 17:00 | 
17:00 - 17:30 | 
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获
- 单词圣手是个好的插件（思想上），体验上并不好。
- 开发出来redux的人真的挺牛逼的
-  [Array.prototype.](https://developer.mozilla.org/zh-CN/docs//JavaScript/Reference/Global_Objects/Array/ReduceRight)的作用是什么? 很神奇的api。
来源[-compose](https://github.com/reactjs//blob/master/src/compose.js)
```
export default function compose() {
  for (var _len = arguments.length, funcs = Array(_len), _key = 0; _key < _len; _key++) {
    funcs[_key] = arguments[_key];
  }

  if (funcs.length === 0) {
    return function (arg) {
      return arg;
    };
  }

  if (funcs.length === 1) {
    return funcs[0];
  }

  var last = funcs[funcs.length - 1];
  var rest = funcs.slice(0, -1);
  return function () {
    return rest.reduceRight(function (composed, f) {
      return f(composed);
    }, last.apply(undefined, arguments));
  };
}
```
- WIP﻿﻿: Work in progress

**Comment by zhouzhongyuan** [comment]
# 20170810
周四

## TODO
- [ ] 和顾老师讨论-ide
    - [x] 设计前端Store结构，越详细越好
    - [x] component与store如何交互
    - [x] store与后台如何交互
## 记录
时间 | 事件
------------ | -------------
08:00 - 08:30 |  走路
08:30 - 09:00 |  整理，复习昨天内容<br /><b>对技术栈的基本内容都有了了解</b><br />可以着手改造react-boilerplate以适应web-ide的需求了
09:00 - 09:30 |  重看，看了阮一峰的文章，写的挺好的
09:30 - 10:00 |  app支付需要支持司机端和客户端，前端后端代码都需要修改。<br />结论：没有讨论出具体的结论。
10:00 - 10:30 |  学习研究react-boilerplate的最后一个核心内容，styled-components.<br />结论：使用material-ui, 而不是styled-components。
10:30 - 11:00 |  重看文章[The ﻿Hitch﻿hiker﻿﻿ Guide to react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/introduction.md)，又有了新的收获。<br />收获：加深了了解，作者很牛逼，能把复杂的问题简单化。<br />应该多看几遍。
11:00 - 11:30 |  yes_ios_2_2_0, update pay parameters
11:30 - 12:00 |  买菜
12:00 - 12:30 |  吃饭
12:30 - 13:00 |  休息
13:00 - 13:30 |  走路
13:30 - 14:00 |  Update ios pay with bundleId parameter, 成功
14:00 - 14:30 |  接着学习文章[The ﻿Hitch﻿hiker﻿﻿ Guide to react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/introduction.md)
14:30 - 15:00 |  浪费了。
15:00 - 15:30 |  第二遍[The ﻿Hitch﻿hiker﻿﻿ Guide to react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/introduction.md)看完了
15:30 - 16:00 | 看react-boilerplate源代码
16:00 - 16:30 | 看react-boilerplate源代码
16:30 - 17:00 | 看react-boilerplate源代码<br />看懂了如何与后台通信，刷新数据
17:00 - 17:30 | 驹华iOS打包
17:30 - 18:00 | 尝试写个脚本来给驹华打包，失败。<br />ios项目中没有明确指定scheme
18:00 - 18:30 |
18:30 - 19:00 | 

## 收获
- 看源代码，要看1.0版本，不要看最新版本
-  [<The ﻿Hitch﻿hiker﻿﻿ Guide to react-boilerplate>](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/introduction.md)读后感
    - 名词
    Dumb component : presental
    Smart component: container
    - 示意图有点过时了，该更新的没有更新。<br />Dumb Component的叫法已经不被推荐了。<br />react-route v4下，项目中已经没有routes.js文件了。
    - [workflow](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/introduction.md#workflow)讲了两个更新的过程，<br />不用费劲看代码了，直接看此说明就能大致理解。
    - 示意图其实很简单，一开始总是怕困难，觉得复杂

## 谨记
-  [x] 晚上11点之前睡觉
-  [x] 中午午休20分钟
-  [x] [标准坐姿，标准距离](http://www.hanjunxing.com/how-to-sit)

**Comment by zhouzhongyuan** [comment]
# 20170811 

周五
## TODO
- [ ] url-loader做了什么？怎么能转换font
## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 |  走路
08:30 - 09:00 |  web-ide开始，环境。
09:00 - 09:30 |  web-ide开始，环境。
09:30 - 10:00 |  web-ide，material-ui
10:00 - 10:30 |  web-ide，material-ui
10:30 - 11:00 |  web-ide，material-ui
11:00 - 11:30 |  走路
11:30 - 12:00 |  走路
12:00 - 12:30 |  吃饭
12:30 - 13:00 |  休息
13:00 - 13:30 |  走路
13:30 - 14:00 | web-ide, router & login page
14:00 - 14:30 | web-ide, login page
14:30 - 15:00 | web-ide, login page
15:00 - 15:30 | 
15:30 - 16:00 | 
16:00 - 16:30 | 
16:30 - 17:00 | 
17:00 - 17:30 | 
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获
- 所有都是自己写，有问题可以参考react-boilerplate。
- [ ] 下午做route、login界面、授权页面、

## 谨记

**Comment by zhouzhongyuan** [comment]
# 20170814
# 20170815
[Yigo 1.6打包压缩流程](https://github.com/zhouzhongyuan/qa/issues/47#issuecomment-322082449)

**Comment by zhouzhongyuan** [comment]
# 20170816
周三

**Comment by zhouzhongyuan** [comment]
# 20170817
周四

- 万华ios一年到期
-  宁波，production 版本，沟通浪费了80%以上的时间

**Comment by zhouzhongyuan** [comment]
# 20170818
周五

- [ ] yigo2.0 web端配置环境(development)

## GridLayoutPanel
- 此Component仅为了自动转换用，手写Component不会使用。
- 会遍历items，遍历出来的item使用DynamicControl，并向其传入yigoid即可。

**Comment by zhouzhongyuan** [comment]
# 20170821 

周一
## TODO

## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 | 走路
08:30 - 09:00 | 复习以前内容
09:00 - 09:30 |  webpack-dev-server,
09:30 - 10:00 |  webpack-dev-server, [config](http://1.1.2.17:8000/svn/yes/webapp/src@14146)
10:00 - 10:30 | 
10:30 - 11:00 | 
11:00 - 11:30 | 
11:30 - 12:00 | 
12:00 - 12:30 | 
12:30 - 13:00 | 
13:00 - 13:30 | 
13:30 - 14:00 | 
14:00 - 14:30 | 
14:30 - 15:00 | 
15:00 - 15:30 | 
15:30 - 16:00 | 
16:00 - 16:30 | 
16:30 - 17:00 | 
17:00 - 17:30 | 
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获

## 谨记

**Comment by zhouzhongyuan** [comment]
# 20170822

周二
## TODO

## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 | 
08:30 - 09:00 | 驹华打包
09:00 - 09:30 | router改变，更新state
09:30 - 10:00 | router改变，更新state, [fixed](https://github.com/zhouzhongyuan/qa/issues/86#issuecomment-321134254).<br />删除Router就好了。<br />实际原因：引用错了，错误地使用了`BrowserRouter`
10:00 - 10:30 | 
10:30 - 11:00 |  夏李俊，微信打开PDF，word等文件。<br />微信浏览器不能打开pdf，doc等。<br />请求报警告：“CAUTION: provisional headers are shown” in Chrome debugger <br />根本原因：微信浏览器发送request请求的时候，请求头不accept pdf<br />解决方法：pdf.js or 转为图片。
11:00 - 11:30 | 
11:30 - 12:00 | 
12:00 - 12:30 | 
12:30 - 13:00 | 
13:00 - 13:30 | 
13:30 - 14:00 | 
14:00 - 14:30 | 
14:30 - 15:00 | 
15:00 - 15:30 | 
15:30 - 16:00 | 
16:00 - 16:30 | 
16:30 - 17:00 | 
17:00 - 17:30 | 
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获
- 今天的额主要工作是： 解决了react-router-redux,不更新store的问题，添加了AddMenu和ProjectNew。
- react自身的优点是组件化，整个页面的逻辑是它的弱点。
- 一个简单只有两个input的页面，如果想要做的好，还是有很多细节需要打磨的。
## 谨记

天合光能账号 087483
