### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zhouzhongyuan** [BokeFE/QA#54]
- [ ] Yigo1.6下载大文件出错。参考[Node.js 中实现HTTP文件下载](https://itbilu.com/nodejs/core/Nkvh9yS4W.html)
- [ ] Yigo1.6 pack服务转成promise，切分代码，结构合理
- [ ] 打包网站中，项目的Svn 不得包含中文文件名或者文件夹，应该加个判断，判断文件名中是否包含中文

- [ ] VPN,忽略1.1.8.*,需要在路由器上写脚本

- [ ] 每个项目都要有发布历史。
