### ISSUE TITLE
dairy(20170823-20170920)

### ISSUE THREAD

**Issue by zhouzhongyuan** [BokeFE/QA#56]
## TODO
- [x] TodoList页面
- [x] Navigation bar
    - [x] title
    - [x] back_button(左上角)
    - [x] Toolbar(右上角)
- [ ] 请假单明细，（审批意见，与web桌面端人员沟通）
- [x] onlyShow
- [ ] 样式取舍。最差就是与设计器一样丑，绝对不能比设计器更丑。
- [x] PropTypes提取到yes中
## 成果
- [ ] 一个 与设计器样式一致（或者，更好看）的、自动生成的、流程跑通的 app端 和 移动web端。

## Intro
- 每周要有一个成果，例如新增了一个页面，例如样式变好看了
username: 087483

**Comment by zhouzhongyuan** [comment]
# 20170823

周三

# 主要工作：Split prop-types into 'yes'
## TODO

## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 | 
08:30 - 09:00 | 
09:00 - 09:30 | 
09:30 - 10:00 |  
10:00 - 10:30 | 
10:30 - 11:00 | 
11:00 - 11:30 | 
11:30 - 12:00 | 
12:00 - 12:30 | 
12:30 - 13:00 | 
13:00 - 13:30 | 
13:30 - 14:00 | 
14:00 - 14:30 | 
14:30 - 15:00 | 
15:00 - 15:30 | 
15:30 - 16:00 | 
16:00 - 16:30 | 
16:30 - 17:00 | 
17:00 - 17:30 | 
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获
- 只是机械性的分离 prop-types
## 谨记

**Comment by zhouzhongyuan** [comment]
# 20170824

周四

## TODO
- [ ] react-navigation, 如何在web下制作一个navBar
    - [ ] 再次熟悉一下[react-navigation](https://github.com/react-community/react-navigation)
    - [ ] 查看顾老师是如何使用web的
    - [ ] 试着自己为stackRouter做一个Component，包含backButton and title
- [x] ios打包支持第三方公司的证书和mobileprovision
一天时间,开始时间10:00
    - [x] 参考appcan
    - [x] 理解各个名词的意思，形成文档，给顾老师讲清楚
- [ ] 修改引入propTypes的方式，改为static的方式
## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 | 走路
08:30 - 09:00 | 等待顾老师，使用不翻墙的网络结束。
09:00 - 09:30 | 
09:30 - 10:00 |  
10:00 - 10:30 | 
10:30 - 11:00 | iOS default payment error
11:00 - 11:30 | iOS default payment error
11:30 - 12:00 | 
12:00 - 12:30 | 
12:30 - 13:00 | 
13:00 - 13:30 | 
13:30 - 14:00 | iOS default payment error
14:00 - 14:30 | iOS default payment error
14:30 - 15:00 | iOS default payment error
15:00 - 15:30 | iOS default payment error
15:30 - 16:00 | iOS default payment error<br />为什么这样一个小bug用了那么长时间？<br />1. iMac特别慢，打一次framework用时接近1小时<br />2. ios程序本身有问题，导致我使用的小屏幕iphone5 不能测试，只能请别人帮忙测试 <br /> 3.对于ios的开发流程不熟悉，这次写了一个[文档](https://github.com/BokeFE/QA/issues/57)<br /> **改进** <br /> 1. 只修改源代码，打包工作应该交给陈志盛来做
16:00 - 16:30 | 和顾老师讨论iOS打包相关概念
16:30 - 17:00 | 和顾老师讨论iOS打包相关概念
17:00 - 17:30 | Prepare for importing p12 file in Mac OSX
17:30 - 18:00 | 
18:00 - 18:30 | 
18:30 - 19:00 | 

## 收获
- 对ios打包相关概念更熟悉了
- 浪费了半天多时间，来解决一个ios 支付的小bug，主要原因不在修改代码，而在调试。恶心。
## 谨记

**Comment by zhouzhongyuan** [comment]
# 20170825 

周五
## TODO
- [ ] react-navigation, 如何在web下制作一个navBar
    - [ ] 再次熟悉一下[react-navigation](https://github.com/react-community/react-navigation)
    - [ ] 查看顾老师是如何使用web的
    - [ ] 试着自己为stackRouter做一个Component，包含backButton and title
- [ ] 修改引入propTypes的方式，改为static的方式
## 记录
时间 | 事件 
------------ | ------------- 
08:00 - 08:30 | 
08:30 - 09:00 | 迟到，走路
09:00 - 09:30 |  ios payment debug
09:30 - 10:00 |  ios payment debug
10:00 - 10:30 |  ios payment debug<br />最后发现是司机端app的urlscheme不对
10:30 - 11:00 |  ios-pack, add import-certificate
11:00 - 11:30 |  ios-pack, add import-certificate

时间 | 事件 
------------ | ------------- 
13:30 - 14:00 |  ios-pack, add import-certificate
14:00 - 14:30 |  ios-pack, add import-certificate
14:30 - 15:00 |  紫江，androidTargetSDKVersion有23将为22，无法升级
15:00 - 15:30 |  紫江，androidTargetSDKVersion有23将为22，无法升级
15:30 - 16:00 |  紫江，androidTargetSDKVersion有23将为22，无法升级
16:00 - 16:30 |  紫江，androidTargetSDKVersion有23将为22，无法升级
16:30 - 17:00 |  紫江，androidTargetSDKVersion有23将为22，无法升级。<br /> 修改打包网站，每个项目可自由选择23 or 22.
17:00 - 17:30 |  工作日志

## 收获
- 沟通真的非常浪费时间啊，最好还是面对面语言沟通

## 谨记
- 沟通真的非常浪费时间啊，最好还是面对面语言沟通

**Comment by zhouzhongyuan** [comment]
# 20170828

周一
## TODO
- [ ] react-navigation, 如何在web下制作一个navBar
    - [ ] 再次熟悉一下[react-navigation](https://github.com/react-community/react-navigation)
    - [ ] 查看顾老师是如何使用web的
    - [ ] 试着自己为stackRouter做一个Component，包含backButton and title
- [ ] 修改引入propTypes的方式，改为static的方式
## 记录

### 上午

时间 | 事件 
------------ | ------------- 
08:30 - 09:00 | react-navigation
09:00 - 09:30 | react-navigation
09:30 - 10:00 | 天合光能证书测试
10:00 - 10:30 | 天合光能证书测试
10:30 - 11:00 | 天合光能证书测试
11:00 - 11:30 | 天合光能证书测试

### 下午

时间 | 事件 
------------ | ------------- 
13:00 - 13:30 |  打包网站1.6代码分离
13:30 - 14:00 |  打包网站1.6代码分离
14:00 - 14:30 |  打包网站1.6代码分离
14:30 - 15:00 |  打包网站1.6代码分离
15:00 - 15:30 |  打包网站1.6代码分离
15:30 - 16:00 |  打包网站1.6代码分离
16:00 - 16:30 |  打包网站1.6代码分离
16:30 - 17:00 |  打包网站1.6代码分离，[成果](https://github.com/zhouzhongyuan/cordova-pack-old)
17:00 - 17:30 | 

## 收获

## 谨记

**Comment by zhouzhongyuan** [comment]
# 20170829

周二


- 打包网站添加，测试import-certificate

**Comment by zhouzhongyuan** [comment]
# 20170830

周三

- TriggerControlView 添加disabled onlyShow支持
- react-navigation 
    - [x] 如何使用？
    - [ ] 大致如何工作的？
    - [ ] web端如果使用，还缺少什么？

**Comment by zhouzhongyuan** [comment]
# 20170831

周四

# TODO

- [ ] react-navigation 
    - [ ] 大致如何工作的？
      - [ ] 总共分多少个文件，多少个类别？
    - [ ] web端如果使用，还缺少什么？
      > 什么都不缺少。关键是如何显示出来TopBar？
- [ ] 保护视力
    - [ ] 注意休息
    - [ ] 找个文章（书），跟着做
- [ ] 理发
## 记录
### 上午
时间 | 事件 
------------ | ------------- 
08:30 - 09:00 | 
09:00 - 09:30 |  搜索买个独立显卡支持双屏，好难搜索，只能在淘宝搜索得到，<br /> 浪费了半小时！！！！！<br />[晚上回家接着搜索](https://s.taobao.com/search?q=%E6%98%BE%E5%8D%A1+OptiPlex+7010+%E5%8F%8C%E5%B1%8F+ubuntu&imgfile=&js=1&stats_click=search_radio_all%3A1&initiative_id=staobaoz_20170831&ie=utf8)
09:30 - 10:00 |  react-navigation
10:00 - 10:30 |  react-navigation
10:30 - 11:00 |  react-navigation
11:00 - 11:30 |  react-navigation,[成果颇多,收获颇多](https://github.com/zhouzhongyuan/qa/issues/51#issuecomment-326164219)
### 下午
时间 | 事件 
------------ | ------------- 
13:00 - 13:30 | 跑通yesdemo,react-native版本
13:30 - 14:00 | 跑通yesdemo,react-native版本
14:00 - 14:30 | 跑通yesdemo,react-native版本
14:30 - 15:00 | 跑通yesdemo,react-native版本<br />登录界面能打开，能登陆。<br />登录之后的第一个页面能渲染，但是主体部分一直是Loading
15:00 - 15:30 |  忘了
15:30 - 16:00 |  忘了
16:00 - 16:30 |  分析代码，找不显示Header的原因
16:30 - 17:00 |  分析代码，找不显示Header的原因
17:00 - 17:30 |  找到不显示Header的原因：`headerMode: 'none',`

## 收获
- router作用？ [映射paths和actions的](https://github.com/zhouzhongyuan/qa/issues/51#issuecomment-326164219)。（言简意赅啊！）

- 现在看react-navigation的代码，感觉非常简单。看每一块都能看明白，怎么有这个转变呢


## 谨记

- 看代码要有记录，不能白看。例如，react-navigation以前看过，现在完全找不到记录，感觉以前的额东西白看了

**Comment by zhouzhongyuan** [comment]
# 20170901

周五
## TODO

## 记录
### 上午
时间 | 事件 
------------ | ------------- 
08:30 - 09:00 |  react-nvigation参数
09:00 - 09:30 |  react-nvigation参数
09:30 - 10:00 |  react-nvigation参数
10:00 - 10:30 |  2.0打包网站，处理bug<br />Provisioning profile \"iOS Team Provisioning Profile: cn.com.broadocean.xmf\" doesn't include signing certificate \"iPhone Developer<br />Code signing is required for product type 'Application' in SDK 'iOS 10.2 
10:30 - 11:00 |  2.0打包网站，处理bug
11:00 - 11:30 |  2.0打包网站，处理bug<br />上午的思路完全错了，我以为是codesign权限错误![a8j8x](https://user-images.githubusercontent.com/717817/29960469-584ac99c-8f2e-11e7-9391-dbe4d368dc7a.png)<br />我做了[unlock-keychain](https://www.npmjs.com/package/mac-keychain), 可能有用，可能无用，聊胜于无。
### 下午
时间 | 事件 
------------ | ------------- 
13:00 - 13:30 |  2.0打包网站，处理bug
13:30 - 14:00 |  2.0打包网站，处理bug
14:00 - 14:30 |  2.0打包网站，处理bug
14:30 - 15:00 |  2.0打包网站，处理bug
15:00 - 15:30 |  2.0打包网站，处理bug
15:30 - 16:00 |  2.0打包网站，处理bug<br />解决方法特别简单：加了一个参数 configuration: Distribution<br />耗费了很长时间处理这个bug, 本来应该1.5h就应该处理好的。<br /> 每测试一次都要15分钟以上<br />没看懂英文的错误提示，是耗费时间的主要原因<br />错误意思：cn.com.broadocean.xmf.mobileprovision不包含iphone Developer证书。<br />要想打包type为"Application"的product，必须签名。 <br />   **错误很简单：mobileprovision与certificate不对应**  <br />  **解决办法很简单：指定certificate即可**
16:00 - 16:30 | 
16:30 - 17:00 | 
17:00 - 17:30 | 

## 收获

## 谨记

**Comment by zhouzhongyuan** [comment]
# 20170904

周一


- 打包网站1.6分离网站和打包服务

**Comment by zhouzhongyuan** [comment]
# 20170905

周二


- Yigo2.0 react-native端，跑通react-navigation相关代码

**Comment by zhouzhongyuan** [comment]
# 20170906

周三


- Yigo2.0 react-native端，跑通other related code
下午：
时间全浪费了。
浪费在跑通yigo设计器上，因为电脑只有4G内存，整整一个下午都跑不通。
# 垃圾电脑害死人
# 垃圾电脑害死人
# 垃圾电脑害死人

**Comment by zhouzhongyuan** [comment]
# 20170907

周四

- 跟顾老师讨论yigo设计器样式转换的问题，
结论： 
    - LinerLayout只有一行或者一列
    - 支持横屏和竖屏的切换
    - 设计器很ugly，连自圆其说都不能做到

- 镇江奇美TMS 证书到期了

**Comment by zhouzhongyuan** [comment]
# 20170908（内部调休，转到下周一做）

- [ ] Yigo2.0, react-native，页面切换时，动画卡主，渲染，动画。
- [ ] NavigatorToolbar.js,如果toolAction为空，那么隐藏

**Comment by zhouzhongyuan** [comment]
# 20170911
周一
- [x] Yigo2.0, react-native，页面切换时，动画卡主，渲染，动画。
- [ ] NavigatorToolbar.js,如果toolAction为空，那么隐藏
- [x] Tab navigation切换动画
- [x] tableviewrowitem添加Divider
## TODO

- [ ] 导航栏颜色，primaryColor （暂时没法做，等后端给颜色）
- [ ] Navigation左侧空白太多

## 问题
1. 网络总是有问题。为什么现在调试这么慢，因为我全局翻墙了。(本机-美国-局域网)

**Comment by zhouzhongyuan** [comment]
# 20170912
周二

- [x]  紫江ios,点击"注销",一直在Loading。改为回到登录页面。整整一个下午，顾老师解决的，我浪费了整整一个下午，啥也没做！

**Comment by zhouzhongyuan** [comment]
# 20170913
周三


- [x]  为什么第二次渲染仍旧这么慢？找到原因。使得第二次渲染比第一次渲染要快。
原因是没有处理好stopEvent。

我需要一个网页标注功能或者PDF标注功能

**Comment by zhouzhongyuan** [comment]
# 20170914
Thursday
- [ ] 总结数据更新过程
- [x] 对代码进行格式化。是今天的主要工作。全都是工作量的问题。

- [x] 08:30-10:00,Modify non-standard file names and variable names
- [ ] What does `Container.create` do?
- [ ] How does our component work?( with the stopEvent )

**Comment by zhouzhongyuan** [comment]
# 20170915
Friday
- [x] Move propTypes to a separated package
- [x] Support ‘pref' in height in GridLayoutPanel

**Comment by zhouzhongyuan** [comment]
# 20170918
Monday
- [x] Archive for dyysapp(08:30-10:00)
- [ ]

**Comment by zhouzhongyuan** [comment]
# 20170919
Tuesday
# 垃圾电脑害死人
# 垃圾电脑害死人
# 垃圾电脑害死人
- [x] Restart mac for mac死机了(09:30-11:00)
- [x] VPN到期了，本来想着自己做个VPN服务器，可以省下来200块钱呢，做了一下午，做成l2tp vpn 服务器。流量可以使用，博科公司的不可以使用，也就是没卵用。
- [x] [公司内网外网自动分流](https://github.com/zhouzhongyuan/vpn/tree/master/pdcn)做好了

**Comment by zhouzhongyuan** [comment]
# 20170920
Wednesday
- [x] [react-navigation 解决导航栏 “待办” 的40px的left](https://github.com/jefferscn/react-navigation/commit/0a34b2a14093f1c1c7ac0fbc3f6145263c67df26)

- [ ] Text component can be edited
When the `TextField` is wrapped with `TouchableHighlight`, the `textarea` can't be focused?
    - [ ] Why `textarea` can't be focused?
    `react-native-web/src/components/Touchable/Touchable.js` `e.preventDefault();`引起的的，

    - [x] Why the `Event Listeners`(chrome devtools)  of `textarea` is "invalid"?
     [invalid - Event reference | MDN](https://developer.mozilla.org/en-US/docs/Web/Events/invalid).There is nothing to do with the 'invalid' event. No mater the wrapped component is `TouchableHighlight`  or `View`, there is `invalid` in  `Event Listeners`(chrome devtools).
    

- [x] 13:30-16:00 pack-serve-1.6, 文件名包含“中文”

**Comment by zhouzhongyuan** [comment]
# 20170921

- 08:30-10:00 事件 stopPropagation preventDefault, 看文章[ React合成事件系统](https://zhuanlan.zhihu.com/p/25883536)及源代码，大致了解了synthetic event是啥。
- 10:00-11:30 react-native-web环境，失败
