### ISSUE TITLE
dairy(0927-0930)

### ISSUE THREAD

**Issue by zhouzhongyuan** [BokeFE/QA#59]

**Comment by zhouzhongyuan** [comment]
# 20170927 

周三
## TODO

## 记录
时间 | 事件 
------------ | ------------- 
08:30 - 09:00 | react-navigation,url打开不同页面
09:00 - 09:30 | react-navigation,url打开不同页面
09:30 - 10:00 |  公司不允许把户口转进来，哎！垃圾！
10:00 - 10:30 |  网络，电话，咨询其他办理户籍的方式
10:30 - 11:00 |  网络，电话，咨询其他办理户籍的方式
11:00 - 11:30 |  网络，电话，咨询其他办理户籍的方式
13:30 - 14:00 | 探究react-navigation源代码，以支持url打开不同页面，这次主要是支持TabNavigator
14:00 - 14:30 | 探究react-navigation源代码，以支持url打开不同页面，这次主要是支持TabNavigator
14:30 - 15:00 | 探究react-navigation源代码，以支持url打开不同页面，这次主要是支持TabNavigator
15:00 - 15:30 | 探究react-navigation源代码，以支持url打开不同页面，这次主要是支持TabNavigator
15:30 - 16:00 | 探究react-navigation源代码，以支持url打开不同页面，这次主要是支持TabNavigator
16:00 - 16:30 | 探究react-navigation源代码，以支持url打开不同页面，这次主要是支持TabNavigator
16:30 - 17:00 | 探究react-navigation源代码，以支持url打开不同页面，这次主要是支持TabNavigator
17:00 - 17:30 | 成果 [How does StackNavigator work?](https://github.com/zhouzhongyuan/qa/issues/51#issuecomment-332431362)。顾老师说不需要支持TabNavigator的url打开。哎，应该早与顾老师沟通的

## 收获

## 谨记
- 要吃早餐

**Comment by zhouzhongyuan** [comment]
# 20170928 

Thursday
## TODO

- [x] Modal
  - [x] 整个Component的modal形式

- Based on [React Native Deep Linking with Nested Navigators – Ivan Zotov – Medium](https://medium.com/@ivanzotov/react-native-deep-linking-with-authorization-screen-drawer-and-nested-navigators-in-react-4f702b1520a0), I make nested navigator work.
- [How to hide header? ](https://github.com/react-community/react-navigation/issues/293#issuecomment-298085480)
  - [x] Modal of Loading
- 参考 [Correct way to create a root Modal? · Issue #1887 · react-community/react-navigation](https://github.com/react-community/react-navigation/issues/1887)
- > Note: If you need more control over how to present modals over the **rest of your app**, then consider using a top-level Navigator.

- [ ] Find a bug in opening component with url,  there is no `HeaderRight`

## 记录
时间 | 事件 
------------ | ------------- 
08:30 - 09:00 |  Organize `history` related content to support opening component with url 
09:00 - 09:30 |  Search method  in react-navigation issues.
09:30 - 10:00 |  Search method  in react-navigation issues.
10:00 - 10:30 |  Search method  in react-navigation issues.
10:30 - 11:00 |  Search method  in react-navigation issues.
11:00 - 11:30 |  Search method  in react-navigation issues.
13:30 - 14:00 | 驹华打包
14:00 - 14:30 |  rouer divided into `card` and `modal`
14:30 - 15:00 |  rouer divided into `card` and `modal`
15:00 - 15:30 |  整个Component的modal形式,做好了。
15:30 - 16:00 |  想美化一下Modal，失败，我果然不擅长这个啊。
16:00 - 16:30 |  Fix  modal of Loading
16:30 - 17:00 |  Fix  modal of Loading
17:00 - 17:30 | 

## 收获

## 谨记
- 要吃早餐

**Comment by zhouzhongyuan** [comment]
# 20170929

Friday

- [x] BusyLoading

**Comment by zhouzhongyuan** [comment]
# 20170930
Saturday

- [ ] Turn off Lingxing's computer at the end of the day

## 谨记
- 看文档，一定要自己做笔记，画图，要不然就是白看。
