### ISSUE TITLE
dairy(1013-1113)

### ISSUE THREAD

**Issue by zhouzhongyuan** [BokeFE/QA#61]
## TODO
- [x] 1. url 与页面完全匹配
- [x] 2. 动画卡顿
- [ ] 5. flex-basis bug
- [x] 8. cells内容全部居右
- [x] 4. Template注册机制
- [x] 6. 表头Button不显示（手机端，只是显示）
- [x] 7. 无Buddykey，不显示Component。（Checkbox除外）
- [x] 3. 访问过多
- [ ] 9. 表格模板 material-ui,参考ListItem
- [ ] 10. ListItem点击两次问题

## TODO 衍生问题
- [ ] 1. react-navigation, native端，mode
- [x] 2. 动画卡顿

**Comment by zhouzhongyuan** [comment]
# Content

**Comment by zhouzhongyuan** [comment]
天合光能目录结构：
```
├── billform（用户自己写）
│   └── index.js
├── config.js
├── DynamicView.js（固定）
├── index.js（固定）
├── page
│   ├── mtodolist.js（用户自己写）
│   └── my.js（用户自己写）
└── template
    ├── defaultTemplateMapping.js（固定）
    ├── index.js
    └── TabTemplate（固定）
        ├── CellLayoutTemplate.js
        ├── getMappedComponentHOC.js
        ├── index.js
        └── TabViewTemplate.js
```

**Comment by zhouzhongyuan** [comment]
# 第二周
- [ ] 1. 反向模板
- [x] 2. ignoredControl
- [ ] 3. 项目结构与开发模式
- [x] 4. native版本cache
- [x] 5. 登录页面，模板
- [ ] 6. Todolist scroll 慢
- [ ] 7. 优化（初始化，重载）
- [ ] 8. Prompt

**Comment by zhouzhongyuan** [comment]
# 20171025

Wendsday

## Mid-tier Mobile

** | First | Second
-- | -- | --
Script|
Rendering|
Painting|

- 打开详情页面3s，其中调用到‘history.push’用时1.2s
